version: "3"
services:

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"
    environment:
      - KAFKA_URL=kafka1:19092
    env_file:
      - env-example/minio.env

  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - INGRESS_TYPE=KAFKA
      - KAFKA_URL=kafka1:19092
      - DISCOVERY_HOST=coordinator
      - DISCOVERY_PORT=8888
      - UNC_LOG_PATH=/usr/local/universalis/unc-logs
    env_file:
      - env-example/minio.env
    volumes:
      - type: 'bind'
        source: './unc_logs'
        target: '/usr/local/universalis/unc-logs'
