apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: NodePort
  selector:
    component: worker
  ports:
    - port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: kpsarakis/universalis-worker:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1"
            requests:
              memory: "1000Mi"
              cpu: "1"
          ports:
            - containerPort: 8888
          env:
            - name: INGRESS_TYPE
              value: "KAFKA"
            - name: KAFKA_URL
              value: "kafka:9092"
            - name: DISCOVERY_HOST
              value: "coordinator-service"
            - name: DISCOVERY_PORT
              value: "8888"
            - name: MINIO_HOST
              value: minio
            - name: MINIO_PORT
              value: '9000'
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"
